name: Update Date JSON

on:
  schedule:
    - cron: "59 18 * * *"  # 毎日 18:59 UTC（JST 3:59）
  workflow_dispatch:  # 手動実行も可能

jobs:
  update-date:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # GITHUB_TOKENに書き込み権限を付与

    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v4

      - name: JSTの現在の日付を取得
        run: |
          TZ=Asia/Tokyo date '+%Y-%m-%d'
          echo "DATE=$(TZ=Asia/Tokyo date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: JSONの更新
        run: |
          jq --arg newDate "$DATE" '.date = $newDate' data.json > tmp.json && mv tmp.json data.json

      - name: 変更をコミット＆プッシュ
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update date to $DATE" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
