name: Update Date JSON

on:
  schedule:
    - cron: "59 18 * * *"  # 毎日 18:59 UTC (JST 3:59)
  workflow_dispatch:  # 手動実行も可能

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v4

      - name: 現在の日付を取得
        run: echo "DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: JSONの更新
        run: |
          jq --arg newDate "$DATE" '.date = $newDate' data.json > tmp.json && mv tmp.json data.json

      - name: 変更をコミット＆プッシュ
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update date to $DATE" || exit 0
          git push
